version: "3.7"

x-env: &env
  NAME: "api"
  NETWORK_NAME: "mainnet"

  API_PORT: "${API_PORT:-8000}"

  # Logging
  LOG_LEVEL: "DEBUG"
  LOG_TO_FILE: "false"
  LOG_FILE_NAME: ""
  LOG_FORMAT: "console"
  LOG_IS_DEVELOPMENT: "true"

  # DB
  DB_DRIVER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "${POSTGRES_EXTRERNAL_PORT:-5432}"
  DB_USER: "postgres"
  DB_PASSWORD: "${POSTGRES_PASSWORD:-changeme}"
  DB_DBNAME: "postgres"
  DB_SSL_MODE: "disable"
  DB_TIMEZONE: "UTC"

  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

services:
  api:
    build:
      context: ${API_CONTEXT:-.}
      target: ${API_TARGET:-prod}
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    environment:
      <<: *env
